/*
 Menu que chama TelaCadastrarProduto com o modelo adequado.
 */
package telas;

/**
 *
 * @author João Víctor
 */
public class CadastrarProduto extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarProduto1
     */
    public CadastrarProduto() {
        initComponents();
        setResizable(false); // maximize button disable
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTexto = new javax.swing.JLabel();
        bttLivros = new javax.swing.JButton();
        bttFilmes = new javax.swing.JButton();
        bttPerifericos = new javax.swing.JButton();
        bttCelulares = new javax.swing.JButton();
        bttComputadores = new javax.swing.JButton();
        bttEletroeletronicos = new javax.swing.JButton();
        bttVestuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Produtos");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/imagens/produto1.png")).getImage());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de Produto", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        lblTexto.setText("Selecione o tipo de produto que será cadastrado:");

        bttLivros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/livro1.png"))); // NOI18N
        bttLivros.setMnemonic('L');
        bttLivros.setText("Livros");
        bttLivros.setDoubleBuffered(true);
        bttLivros.setFocusable(false);
        bttLivros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bttLivros.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bttLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttLivrosActionPerformed(evt);
            }
        });

        bttFilmes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/filme1.png"))); // NOI18N
        bttFilmes.setMnemonic('F');
        bttFilmes.setText("Filmes");
        bttFilmes.setFocusable(false);
        bttFilmes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bttFilmes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bttFilmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttFilmesActionPerformed(evt);
            }
        });

        bttPerifericos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/periferico1.png"))); // NOI18N
        bttPerifericos.setMnemonic('P');
        bttPerifericos.setText("Periféricos");
        bttPerifericos.setFocusable(false);
        bttPerifericos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bttPerifericos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bttPerifericos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttPerifericosActionPerformed(evt);
            }
        });

        bttCelulares.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/celular1.png"))); // NOI18N
        bttCelulares.setMnemonic('C');
        bttCelulares.setText("Celulares");
        bttCelulares.setFocusable(false);
        bttCelulares.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bttCelulares.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bttCelulares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttCelularesActionPerformed(evt);
            }
        });

        bttComputadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/computador 1.png"))); // NOI18N
        bttComputadores.setMnemonic('O');
        bttComputadores.setText("Computadores");
        bttComputadores.setFocusable(false);
        bttComputadores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bttComputadores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bttComputadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttComputadoresActionPerformed(evt);
            }
        });

        bttEletroeletronicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/eletroeletronicos1.png"))); // NOI18N
        bttEletroeletronicos.setMnemonic('E');
        bttEletroeletronicos.setText("Eletroeletrônicos");
        bttEletroeletronicos.setFocusable(false);
        bttEletroeletronicos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bttEletroeletronicos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bttEletroeletronicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttEletroeletronicosActionPerformed(evt);
            }
        });

        bttVestuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vestuario1.png"))); // NOI18N
        bttVestuario.setMnemonic('V');
        bttVestuario.setText("Vestuário");
        bttVestuario.setFocusable(false);
        bttVestuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bttVestuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bttVestuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttVestuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(bttComputadores)
                .addGap(18, 18, 18)
                .addComponent(bttEletroeletronicos)
                .addGap(18, 18, 18)
                .addComponent(bttVestuario, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(bttLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTexto)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bttFilmes, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(bttPerifericos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(bttCelulares, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTexto)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttFilmes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttLivros, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttPerifericos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttCelulares, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bttEletroeletronicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttComputadores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttVestuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bttLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttLivrosActionPerformed
        new TelaCadastrarProduto("livro").setVisible(true);
    }//GEN-LAST:event_bttLivrosActionPerformed

    private void bttFilmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttFilmesActionPerformed
        new TelaCadastrarProduto("filme").setVisible(true);
    }//GEN-LAST:event_bttFilmesActionPerformed

    private void bttPerifericosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttPerifericosActionPerformed
        new TelaCadastrarProduto("periferico").setVisible(true);
    }//GEN-LAST:event_bttPerifericosActionPerformed

    private void bttCelularesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCelularesActionPerformed
        new TelaCadastrarProduto("celular").setVisible(true);
    }//GEN-LAST:event_bttCelularesActionPerformed

    private void bttComputadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttComputadoresActionPerformed
        new TelaCadastrarProduto("computador").setVisible(true);
    }//GEN-LAST:event_bttComputadoresActionPerformed

    private void bttEletroeletronicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttEletroeletronicosActionPerformed
        new TelaCadastrarProduto("eletroeletronico").setVisible(true);
    }//GEN-LAST:event_bttEletroeletronicosActionPerformed

    private void bttVestuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttVestuarioActionPerformed
        new TelaCadastrarProduto("vestuario").setVisible(true);
    }//GEN-LAST:event_bttVestuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttCelulares;
    private javax.swing.JButton bttComputadores;
    private javax.swing.JButton bttEletroeletronicos;
    private javax.swing.JButton bttFilmes;
    private javax.swing.JButton bttLivros;
    private javax.swing.JButton bttPerifericos;
    private javax.swing.JButton bttVestuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTexto;
    // End of variables declaration//GEN-END:variables
}
